site_name: 股票学习文档
site_url: https://hellowac.github.io/stock_doc/
nav:
    - 股票:
      - 股票投资基础知识: 
        - 什么是炒股: stock_base/what_stock.md
        - 必须知道的概念: stock_base/must_know_concept.md
        - 必懂的交易规则: stock_base/must_know_trading_rule.md
        - 估值指标市盈率: stock_base/valuation_pe_ratio.md
        - 估值指标市净率: stock_base/valuation_pb_ratio.md
        - 估值指标市销率: stock_base/valuation_ps_ratio.md
        - 估值指标市现率: stock_base/valuation_pcf_ratio.md
        - 估值指标PEG: stock_base/valuation_peg_ratio.md
        - 了解k线图: stock_base/know_k_graph.md
        - 必须掌握的20种K线形态: stock_base/know_20_k_graph.md
        - 经典的看涨K线组合: stock_base/up_k_graph.md
        - 经典的看跌K线组合: stock_base/down_k_graph.md
        - 一文了解均线: stock_base/know_moving_average.md
        - 均线使用中的常用知识: stock_base/common_used_moving_average.md
        - 均线排列的含义: stock_base/moving_average_meaning.md
        - 应对主力K线骗线的几种方法: stock_base/response_mainforce_cheat.md
        - 如何利用均线判断股票的回调力度强弱: stock_base/know_mvoing_average_choice.md
        - 常见的均线“买入”信号有哪些？: stock_base/know_buy_by_moving_average.md
        - 常见的均线“卖出”信号有哪些？: stock_base/know_sale_by_moving_average.md
        - 5日均线的常见用法有哪些？: stock_base/know_five_moving_average_usage.md
        - 什么是布林线？: stock_base/know_bolling_bands.md
        - 布林线下轨的常见用法有哪些？: stock_base/boll_down_usage.md
        - 布林线的上、下开口形态: stock_base/boll_up_and_down_opening.md
        - 布林线的喇叭口形态: stock_base/boll_flare_pattern.md
        - 什么是MACD？: stock_base/what_is_macd.md
        - MACD形态之顶背离: stock_base/macd_top_divergence.md
        - MACD形态之底背离: stock_base/macd_down_divergence.md
      - 筹码分布:
        - 分布形态之双峰填谷: chip_distribution/double_peaks_and_valleys.md
    - 关于: 
      - 制作方式: index.md
      - 主题: about.md
theme: 
  name: 'material'
  language: zh
  features:
    - announce.dismiss
# theme: readthedocs