site_name: 证券学习文档
site_url: https://hellowac.github.io/stock_doc/
nav:
  - 认识商业:
    - 理解会计和财务指标:
      - 会计: business/account/base.md
      - 关键的财务报表: business/account/statements.md
      - 分析财务报表: business/account/analyze_statements.md
  - 股票:
    - 股票投资基础知识: 
      - 什么是炒股: stock_base/what_stock.md
      - 必须知道的概念: stock_base/must_know_concept.md
      - 必懂的交易规则: stock_base/must_know_trading_rule.md
      - 估值指标市盈率: stock_base/valuation_pe_ratio.md
      - 估值指标市净率: stock_base/valuation_pb_ratio.md
      - 估值指标市销率: stock_base/valuation_ps_ratio.md
      - 估值指标市现率: stock_base/valuation_pcf_ratio.md
      - 估值指标PEG: stock_base/valuation_peg_ratio.md
      - 了解k线图: stock_base/know_k_graph.md
      - 必须掌握的20种K线形态: stock_base/know_20_k_graph.md
      - 经典的看涨K线组合: stock_base/up_k_graph.md
      - 经典的看跌K线组合: stock_base/down_k_graph.md
      - 一文了解均线: stock_base/know_moving_average.md
      - 均线使用中的常用知识: stock_base/common_used_moving_average.md
      - 均线排列的含义: stock_base/moving_average_meaning.md
      - 应对主力K线骗线的几种方法: stock_base/response_mainforce_cheat.md
      - 如何利用均线判断股票的回调力度强弱: stock_base/know_mvoing_average_choice.md
      - 常见的均线“买入”信号有哪些？: stock_base/know_buy_by_moving_average.md
      - 常见的均线“卖出”信号有哪些？: stock_base/know_sale_by_moving_average.md
      - 5日均线的常见用法有哪些？: stock_base/know_five_moving_average_usage.md
      - 什么是布林线？: stock_base/know_bolling_bands.md
      - 布林线下轨的常见用法有哪些？: stock_base/boll_down_usage.md
      - 布林线的上、下开口形态: stock_base/boll_up_and_down_opening.md
      - 布林线的喇叭口形态: stock_base/boll_flare_pattern.md
      - 什么是MACD？: stock_base/what_is_macd.md
      - MACD形态之顶背离: stock_base/macd_top_divergence.md
      - MACD形态之底背离: stock_base/macd_down_divergence.md
    - 均线策略:
      - 为什么说均线是神奇的线?（上）: stock_base/average_line/01_base.md
      - 为什么说均线是神奇的线？（下）: stock_base/average_line/02_base.md
      - 均线不同排列形态意味着什么？（上）: stock_base/average_line/03_base.md
      - 均线不同排列形态意味着什么？（下）: stock_base/average_line/04_base.md
      - 格兰威尔八大买卖法则（上）: stock_base/average_line/05_base.md
      - 格兰威尔八大买卖法则（下）: stock_base/average_line/06_base.md
      - 双均线战法（上）-单均线VS双均线: stock_base/average_line/07_base.md
      - 双均线战法（下）-双均线战法应用技巧: stock_base/average_line/08_base.md
      - 三均线战法（上）: stock_base/average_line/09_base.md
      - 三均线战法（下）: stock_base/average_line/10_base.md
      - 一通百通，均线战法很轻松: stock_base/average_line/11_base.md
    - 筹码分布:
      - 分布形态之双峰填谷: chip_distribution/double_peaks_and_valleys.md
  - 债券:
    - 可转债: 
      - 可转债基础: bond/convertible_bonds/01_base.md
      - 中签和收益: bond/convertible_bonds/02_subscription.md
      - 获利方式: bond/convertible_bonds/03_how_to_profit.md
      - 相关常识: bond/convertible_bonds/04_moment_sense.md
      - 计算溢价率: bond/convertible_bonds/05_cal_permium_rate.md
      - 计算溢价率2: bond/convertible_bonds/06_cal_permium_rate.md
      - 债性: bond/convertible_bonds/07_debt.md
      - 风险: bond/convertible_bonds/08_risk.md
  - 关于: 
    - 制作方式: index.md
    - 主题: about.md
theme: 
  name: 'material'
  language: zh
  features:
    - announce.dismiss
# theme: readthedocs