site_name: 证券学习文档
site_url: https://hellowac.github.io/stock_doc/
nav:
  - 认识商业:
    - 理解会计和财务指标:
      - 会计: business/account/base.md
      - 关键的财务报表: business/account/statements.md
      - 分析财务报表: business/account/analyze_statements.md
      - 总结: business/account/summarize.md
    - 财务管理:
      - 财务和财务管理者的角色: business/manage/role.md
      - 财务规划: business/manage/planning.md
      - 运营资金的必要性: business/manage/operating_expenses.md
      - 取得短期融资: business/manage/short_financing.md
      - 取得长期融资: business/manage/lang_financing.md
      - 总结: business/manage/summarize.md
    - 证券市场:
      - 前言: business/stockmarket/foreword.md
      - 证券市场的功能: business/stockmarket/function.md
      - 证券交易所: business/stockmarket/exchange.md
      - 股权融资: business/stockmarket/financing.md
      - 发行债券融资: business/stockmarket/bond.md
      - 投资者如何购买证券: business/stockmarket/buy.md
      - 投资股票: business/stockmarket/investstock.md
      - 投资债券: business/stockmarket/investbond.md
      - 投资基金: business/stockmarket/investfund.md
      - 了解股市指标: business/stockmarket/indicators.md
      - 总结: business/stockmarket/summarize.md
    - 货币、金融机构和美联储:
      - 前言: business/mechanism/foreword.md
      - 货币为什么重要: business/mechanism/matters.md
      - 控制货币供给: business/mechanism/moneysupply.md
      - 银行史与美联储存在的必要性: business/mechanism/existence.md
      - 美国的银行体系: business/mechanism/banksystem.md
      - 最近的银行危机和政府的保护举措: business/mechanism/protections.md
      - 利用技术提高银行效率: business/mechanism/bankefficiency.md
      - 国际银行及其服务: business/mechanism/bankservices.md
      - 总 结: business/mechanism/summarize.md
  - K线图技术:
    - 7章:持续形态: candlestick/persistentpattern.md
    - 8章:神奇的十字星: candlestick/crosshair.md
    - 9章:蜡烛图技术汇总: candlestick/summary.md
    - 10章:蜡烛图信号的汇聚: candlestick/convergence.md
    - 11章:蜡烛图与趋势线: candlestick/klineandtrendlines.md
    - 12章:蜡烛图与百分比回撤水平: candlestick/percentdrawdown.md
    - 13章:蜡烛图与移动平均线: candlestick/movingaverages.md
    - 14章:蜡烛图与摆动指数: candlestick/oscillators.md
    - 15章:蜡烛图与交易量: candlestick/klineandvolume.md
    - 16章:测算价格目标: candlestick/pricetarget.md
    - 17章:相互验证的力量: candlestick/mutualverification.md
    - 蜡烛图技术术语及示意图: candlestick/glossarya.md
  - 周期:
    - 铁律: cycle/ironlaw.md
    - 月份周期:
      - 一月: cycle/month/january.md
      - 二月: cycle/month/february.md
      - 三月: cycle/month/march.md
      - 四月: cycle/month/april.md
      - 五月: cycle/month/may.md
      - 六月: cycle/month/june.md
      - 七月: cycle/month/july.md
      - 八月: cycle/month/august.md
      - 九月: cycle/month/september.md
      - 十月: cycle/month/october.md
      - 十一月: cycle/month/november.md
      - 十二月: cycle/month/december.md
    - 行业周期:
      - 强周期行业: cycle/industry/strong.md
      - 弱周期行业: cycle/industry/weak.md
      - 成长性行业: cycle/industry/growth.md
  - 股票:
    - 代码前缀合集: stock/base/code_prefix.md
    - 股票投资基础知识: 
      - 什么是炒股: stock/base/what_stock.md
      - 必须知道的概念: stock/base/must_know_concept.md
      - 必懂的交易规则: stock/base/must_know_trading_rule.md
      - 估值指标市盈率: stock/base/valuation_pe_ratio.md
      - 估值指标市净率: stock/base/valuation_pb_ratio.md
      - 估值指标市销率: stock/base/valuation_ps_ratio.md
      - 估值指标市现率: stock/base/valuation_pcf_ratio.md
      - 估值指标PEG: stock/base/valuation_peg_ratio.md
      - 了解k线图: stock/base/know_k_graph.md
      - 必须掌握的20种K线形态: stock/base/know_20_k_graph.md
      - 经典的看涨K线组合: stock/base/up_k_graph.md
      - 经典的看跌K线组合: stock/base/down_k_graph.md
      - 一文了解均线: stock/base/know_moving_average.md
      - 均线使用中的常用知识: stock/base/common_used_moving_average.md
      - 均线排列的含义: stock/base/moving_average_meaning.md
      - 应对主力K线骗线的几种方法: stock/base/response_mainforce_cheat.md
      - 如何利用均线判断股票的回调力度强弱: stock/base/know_mvoing_average_choice.md
      - 常见的均线“买入”信号有哪些？: stock/base/know_buy_by_moving_average.md
      - 常见的均线“卖出”信号有哪些？: stock/base/know_sale_by_moving_average.md
      - 5日均线的常见用法有哪些？: stock/base/know_five_moving_average_usage.md
      - 什么是布林线？: stock/base/know_bolling_bands.md
      - 布林线下轨的常见用法有哪些？: stock/base/boll_down_usage.md
      - 布林线的上、下开口形态: stock/base/boll_up_and_down_opening.md
      - 布林线的喇叭口形态: stock/base/boll_flare_pattern.md
      - 什么是MACD？: stock/base/what_is_macd.md
      - MACD形态之顶背离: stock/base/macd_top_divergence.md
      - MACD形态之底背离: stock/base/macd_down_divergence.md
      - 国泰君安主力透视: stock/base/gtja_zldc.md
    - 均线策略:
      - 常用的均线有哪些？: stock/average_line/00_common_use_line.md
      - 为什么说均线是神奇的线?（上）: stock/average_line/01_base.md
      - 为什么说均线是神奇的线？（下）: stock/average_line/02_base.md
      - 均线不同排列形态意味着什么？（上）: stock/average_line/03_base.md
      - 均线不同排列形态意味着什么？（下）: stock/average_line/04_base.md
      - 格兰威尔八大买卖法则（上）: stock/average_line/05_base.md
      - 格兰威尔八大买卖法则（下）: stock/average_line/06_base.md
      - 双均线战法（上）-单均线VS双均线: stock/average_line/07_base.md
      - 双均线战法（下）-双均线战法应用技巧: stock/average_line/08_base.md
      - 三均线战法（上）: stock/average_line/09_base.md
      - 三均线战法（下）: stock/average_line/10_base.md
      - 一通百通，均线战法很轻松: stock/average_line/11_base.md
    - 筹码分布:
      - 分布形态之双峰填谷: chip_distribution/double_peaks_and_valleys.md
    - 技术文章:
      - 可能翻倍的股票: stock/tech_article/stock_that_could_double.md
      - 分时图表买点技巧: stock/tech_article/time_chart_buy_skill.md
      - 股票出现“蚂蚁上树”形态: stock/tech_article/ant_on_the_tree.md
      - 一个短线操作方法: stock/tech_article/short_op.md
      - k线与成交量有什么关系: stock/tech_article/k_and_volume.md
      - 5分钟，15分钟，30分钟，60分钟线分别说明什么？: stock/tech_article/5_15_30_60.md
      - 四连阳抓涨停: stock/tech_article/silianyang_catches_the_daily_limit.md
      - 主力出货手法: stock/tech_article/main_shipping_method.md
      - 图解短线3要素: stock/tech_article/graphical_short_line_3_elements.md
      - 让分时图决定买卖: stock/tech_article/time_chart_decide_the_buying_and_selling.md
      - 出现这3种形态不能买: stock/tech_article/not_buy_three_kline.md
      - 分时图使用技巧: stock/tech_article/time_line_chart_skill.md
  - 债券:
    - 可转债: 
      - 可转债基础: bond/convertible_bonds/01_base.md
      - 中签和收益: bond/convertible_bonds/02_subscription.md
      - 获利方式: bond/convertible_bonds/03_how_to_profit.md
      - 相关常识: bond/convertible_bonds/04_moment_sense.md
      - 计算溢价率: bond/convertible_bonds/05_cal_permium_rate.md
      - 计算溢价率2: bond/convertible_bonds/06_cal_permium_rate.md
      - 债性: bond/convertible_bonds/07_debt.md
      - 风险: bond/convertible_bonds/08_risk.md
  - 龙头股:
    - 新能源: articles/new_energy.md
  - 同花顺:
    - 股票分类:
      - 同花顺行业: ths/同花顺行业.md
      - 证监会行业: ths/证监会行业.md
      - 地域: ths/地域.md
      - 概念: ths/概念.md
    - 行情中心: ths/行情中心.md
  - 家装:
    - 装修购买清单: home/装修购买清单.md
    - 全包概念: home/全包概念.md
  - 统考:
    - 企业经营战略: exam/企业经营战略.md
  - 关于: 
    - 制作方式: index.md
    - 主题: about.md
theme: 
  name: 'material'
  language: zh
  features:
    - announce.dismiss
# theme: readthedocs